DROP DATABASE IF EXISTS manage_db;

CREATE DATABASE manage_db;

USE manage_db;

CREATE TABLE department (
id INT NOT NULL,
name VARCHAR(45) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE roles (
id INT NOT NULL,
title VARCHAR(40) NOT NULL,
salary INT NOT NULL,
deptID INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (deptId) REFERENCES department(id) ON DELETE CASCADE
);

CREATE TABLE employee (
id INT NOT NULL,
firstName VARCHAR(40) NOT NULL,
lastName VARCHAR(40) NOT NULL,
roleID INT NOT NULL,
managerID INT NULL,
PRIMARY KEY (id),
FOREIGN KEY (roleID) REFERENCES roles(id) ON DELETE CASCADE,
FOREIGN KEY (managerId) REFERENCES employee(id) ON DELETE SET NULL
);


